"""recreate dashboard_insights table

Revision ID: 78cb98f43ce0
Revises: d30a8bcb1cb3
Create Date: 2026-07-21 21:21:19.544415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cb98f43ce0'
down_revision = 'd30a8bcb1cb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=False),
    sa.Column('insight_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_insights_business_id'), 'dashboard_insights', ['business_id'], unique=False)
    op.create_index(op.f('ix_dashboard_insights_data_hash'), 'dashboard_insights', ['data_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_insights_data_hash'), table_name='dashboard_insights')
    op.drop_index(op.f('ix_dashboard_insights_business_id'), table_name='dashboard_insights')
    op.drop_table('dashboard_insights')
    # ### end Alembic commands ###
