"""add anomaly flags

Revision ID: c07e52ec8bef
Revises: cdf6cae3c26c
Create Date: 2026-07-21 20:48:54.103436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c07e52ec8bef'
down_revision = 'cdf6cae3c26c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dashboard_insights_business_id', table_name='dashboard_insights')
    op.drop_index('ix_dashboard_insights_data_hash', table_name='dashboard_insights')
    op.drop_table('dashboard_insights')
    op.alter_column('accounts', 'masked_account_number',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='e.g. XXXXXXXX6053 — safe to store unencrypted',
               existing_nullable=True)
    op.alter_column('accounts', 'account_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='SAVINGS / CURRENT / OVERDRAFT / CC — from AA Summary.type',
               existing_nullable=True)
    op.alter_column('accounts', 'ifsc_code',
               existing_type=sa.VARCHAR(length=11),
               comment=None,
               existing_comment='Bank IFSC code',
               existing_nullable=True)
    op.alter_column('accounts', 'balance',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Latest known balance in minor units (paise)',
               existing_nullable=True)
    op.alter_column('accounts', 'balance_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of the balance snapshot from AA Summary.balanceDateTime',
               existing_nullable=True)
    op.alter_column('consent_audit_log', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key',
               existing_nullable=False)
    op.alter_column('consent_audit_log', 'token_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK → consent_tokens.id',
               existing_nullable=False)
    op.alter_column('consent_audit_log', 'business_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK → businesses.id (denormalised for fast audit queries)',
               existing_nullable=False)
    op.alter_column('consent_audit_log', 'action',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='MINTED | RESOLVED | REVOKED | EXPIRED',
               existing_nullable=False)
    op.alter_column('consent_audit_log', 'actor',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Who performed the action: business UUID or "resolver" or "system"',
               existing_nullable=True)
    op.alter_column('consent_audit_log', 'resolved_scope',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Scope that was revealed on RESOLVED events',
               existing_nullable=True)
    op.alter_column('consent_audit_log', 'requester_ip',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='IP address of the token resolver (RESOLVED events only)',
               existing_nullable=True)
    op.alter_column('consent_audit_log', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Extra context: user-agent, request headers, etc.',
               existing_nullable=True)
    op.drop_index('ix_consent_audit_token_created', table_name='consent_audit_log')
    op.create_index('ix_consent_audit_token_created', 'consent_audit_log', ['token_id', 'created_at'], unique=False)
    op.alter_column('consent_tokens', 'snapshot_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Score payload captured at mint time (SNAPSHOT scope only)',
               existing_nullable=True)
    op.alter_column('consent_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of first (and only) resolution for SNAPSHOT tokens',
               existing_nullable=True)
    op.alter_column('counterparties', 'identifier_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='VPA / GSTIN / ACCOUNT_IFSC / PAN / PHONE',
               existing_nullable=True)
    op.alter_column('counterparties', 'identifier_hmac',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='HMAC blind index of identifier for cross-source counterparty matching',
               existing_nullable=True)
    op.alter_column('counterparties', 'source_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Which connector discovered this counterparty: AA / GSTN / RAZORPAY / ZOHO',
               existing_nullable=True)
    op.drop_index('ix_counterparties_biz_idtype_hmac', table_name='counterparties', postgresql_where='(identifier_hmac IS NOT NULL)')
    op.alter_column('invoices', 'external_id_hmac',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Blind index of Zoho invoice ID via pii.BlindIndex()',
               existing_nullable=True)
    op.alter_column('invoices', 'invoice_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='RECEIVABLE / PAYABLE',
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Amount in paise',
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='DRAFT / SENT / OVERDUE / PAID / VOID',
               existing_nullable=False)
    op.drop_index('ix_invoices_external_id_hmac', table_name='invoices', postgresql_where='(external_id_hmac IS NOT NULL)')
    op.create_unique_constraint(None, 'invoices', ['external_id_hmac'])
    op.add_column('score_snapshots', sa.Column('anomaly_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('score_snapshots', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Primary key',
               existing_nullable=False)
    op.alter_column('score_snapshots', 'business_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK → businesses.id',
               existing_nullable=False)
    op.alter_column('score_snapshots', 'score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Credit score 300–850 (Indian bureau scale)',
               existing_nullable=False)
    op.alter_column('score_snapshots', 'confidence',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='LOW | MEDIUM | HIGH — data-richness signal',
               existing_nullable=False)
    op.alter_column('score_snapshots', 'model_version',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Model artifact version string (e.g. linear-v1.0.0)',
               existing_nullable=False)
    op.alter_column('score_snapshots', 'drivers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='SHAP driver breakdown: [{feature, label, direction, impact, raw_value, human_note}]',
               existing_nullable=True)
    op.alter_column('score_snapshots', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the Rust scoring service produced this result',
               existing_nullable=False)
    op.alter_column('score_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row insertion timestamp',
               existing_nullable=False)
    op.drop_index('ix_score_snapshots_biz_computed', table_name='score_snapshots')
    op.create_index('ix_score_snapshots_biz_computed', 'score_snapshots', ['business_id', 'computed_at'], unique=False)
    op.drop_column('score_snapshots', 'ai_explanation')
    op.alter_column('tax_filings', 'return_type',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='GSTR3B / GSTR1 / GSTR2A',
               existing_nullable=False)
    op.alter_column('tax_filings', 'period',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='YYYY-MM format e.g. 2025-06',
               existing_nullable=False)
    op.alter_column('tax_filings', 'gross_turnover',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Turnover in paise',
               existing_nullable=True)
    op.alter_column('tax_filings', 'tax_paid',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Tax paid in paise',
               existing_nullable=True)
    op.alter_column('tax_filings', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='FILED / PENDING / LATE',
               existing_nullable=False)
    op.alter_column('tax_filings', 'raw_data_sealed',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='age-encrypted full return JSON via pii.SealBlob()',
               existing_nullable=True)
    op.alter_column('transactions', 'transactional_balance',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Running balance after this transaction in minor units (paise)',
               existing_nullable=True)
    op.alter_column('transactions', 'mode',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Rebit transaction mode: UPI/NEFT/RTGS/IMPS/NACH/ATM/CARD/CHEQUE/ECS/OTHERS',
               existing_nullable=True)
    op.alter_column('transactions', 'value_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Settlement/value date — may differ from transaction timestamp',
               existing_nullable=True)
    op.alter_column('transactions', 'narration',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Raw bank narration — asymmetrically encrypted (age sealed-box, base64)',
               existing_nullable=True)
    op.alter_column('transactions', 'external_id_hmac',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='HMAC-SHA256(blind_index_key, external_txn_id) — dedup, not PII',
               existing_nullable=True)
    op.alter_column('transactions', 'revenue_role',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='primary = counts toward cash flow; informational = reconciliation-only; tax_summary = GST aggregate',
               existing_nullable=False,
               existing_server_default=sa.text("'primary'::character varying"))
    op.drop_index('ix_transactions_external_id_hmac', table_name='transactions', postgresql_where='(external_id_hmac IS NOT NULL)')
    op.drop_index('ix_transactions_account_timestamp', table_name='transactions')
    op.create_index('ix_transactions_account_timestamp', 'transactions', ['account_id', 'timestamp'], unique=False)
    op.create_unique_constraint(None, 'transactions', ['external_id_hmac'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_index('ix_transactions_account_timestamp', table_name='transactions')
    op.create_index('ix_transactions_account_timestamp', 'transactions', ['account_id', sa.text('timestamp DESC')], unique=False)
    op.create_index('ix_transactions_external_id_hmac', 'transactions', ['external_id_hmac'], unique=True, postgresql_where='(external_id_hmac IS NOT NULL)')
    op.alter_column('transactions', 'revenue_role',
               existing_type=sa.VARCHAR(),
               comment='primary = counts toward cash flow; informational = reconciliation-only; tax_summary = GST aggregate',
               existing_nullable=False,
               existing_server_default=sa.text("'primary'::character varying"))
    op.alter_column('transactions', 'external_id_hmac',
               existing_type=sa.VARCHAR(),
               comment='HMAC-SHA256(blind_index_key, external_txn_id) — dedup, not PII',
               existing_nullable=True)
    op.alter_column('transactions', 'narration',
               existing_type=sa.TEXT(),
               comment='Raw bank narration — asymmetrically encrypted (age sealed-box, base64)',
               existing_nullable=True)
    op.alter_column('transactions', 'value_date',
               existing_type=sa.DATE(),
               comment='Settlement/value date — may differ from transaction timestamp',
               existing_nullable=True)
    op.alter_column('transactions', 'mode',
               existing_type=sa.VARCHAR(),
               comment='Rebit transaction mode: UPI/NEFT/RTGS/IMPS/NACH/ATM/CARD/CHEQUE/ECS/OTHERS',
               existing_nullable=True)
    op.alter_column('transactions', 'transactional_balance',
               existing_type=sa.BIGINT(),
               comment='Running balance after this transaction in minor units (paise)',
               existing_nullable=True)
    op.alter_column('tax_filings', 'raw_data_sealed',
               existing_type=sa.TEXT(),
               comment='age-encrypted full return JSON via pii.SealBlob()',
               existing_nullable=True)
    op.alter_column('tax_filings', 'status',
               existing_type=sa.VARCHAR(),
               comment='FILED / PENDING / LATE',
               existing_nullable=False)
    op.alter_column('tax_filings', 'tax_paid',
               existing_type=sa.BIGINT(),
               comment='Tax paid in paise',
               existing_nullable=True)
    op.alter_column('tax_filings', 'gross_turnover',
               existing_type=sa.BIGINT(),
               comment='Turnover in paise',
               existing_nullable=True)
    op.alter_column('tax_filings', 'period',
               existing_type=sa.VARCHAR(),
               comment='YYYY-MM format e.g. 2025-06',
               existing_nullable=False)
    op.alter_column('tax_filings', 'return_type',
               existing_type=sa.VARCHAR(),
               comment='GSTR3B / GSTR1 / GSTR2A',
               existing_nullable=False)
    op.add_column('score_snapshots', sa.Column('ai_explanation', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('ix_score_snapshots_biz_computed', table_name='score_snapshots')
    op.create_index('ix_score_snapshots_biz_computed', 'score_snapshots', ['business_id', sa.text('computed_at DESC')], unique=False)
    op.alter_column('score_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row insertion timestamp',
               existing_nullable=False)
    op.alter_column('score_snapshots', 'computed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the Rust scoring service produced this result',
               existing_nullable=False)
    op.alter_column('score_snapshots', 'drivers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='SHAP driver breakdown: [{feature, label, direction, impact, raw_value, human_note}]',
               existing_nullable=True)
    op.alter_column('score_snapshots', 'model_version',
               existing_type=sa.VARCHAR(),
               comment='Model artifact version string (e.g. linear-v1.0.0)',
               existing_nullable=False)
    op.alter_column('score_snapshots', 'confidence',
               existing_type=sa.VARCHAR(),
               comment='LOW | MEDIUM | HIGH — data-richness signal',
               existing_nullable=False)
    op.alter_column('score_snapshots', 'score',
               existing_type=sa.INTEGER(),
               comment='Credit score 300–850 (Indian bureau scale)',
               existing_nullable=False)
    op.alter_column('score_snapshots', 'business_id',
               existing_type=sa.UUID(),
               comment='FK → businesses.id',
               existing_nullable=False)
    op.alter_column('score_snapshots', 'id',
               existing_type=sa.UUID(),
               comment='Primary key',
               existing_nullable=False)
    op.drop_column('score_snapshots', 'anomaly_flags')
    op.drop_constraint(None, 'invoices', type_='unique')
    op.create_index('ix_invoices_external_id_hmac', 'invoices', ['external_id_hmac'], unique=True, postgresql_where='(external_id_hmac IS NOT NULL)')
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(),
               comment='DRAFT / SENT / OVERDUE / PAID / VOID',
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.BIGINT(),
               comment='Amount in paise',
               existing_nullable=False)
    op.alter_column('invoices', 'invoice_type',
               existing_type=sa.VARCHAR(),
               comment='RECEIVABLE / PAYABLE',
               existing_nullable=False)
    op.alter_column('invoices', 'external_id_hmac',
               existing_type=sa.VARCHAR(),
               comment='Blind index of Zoho invoice ID via pii.BlindIndex()',
               existing_nullable=True)
    op.create_index('ix_counterparties_biz_idtype_hmac', 'counterparties', ['business_id', 'identifier_type', 'identifier_hmac'], unique=True, postgresql_where='(identifier_hmac IS NOT NULL)')
    op.alter_column('counterparties', 'source_type',
               existing_type=sa.VARCHAR(),
               comment='Which connector discovered this counterparty: AA / GSTN / RAZORPAY / ZOHO',
               existing_nullable=True)
    op.alter_column('counterparties', 'identifier_hmac',
               existing_type=sa.VARCHAR(),
               comment='HMAC blind index of identifier for cross-source counterparty matching',
               existing_nullable=True)
    op.alter_column('counterparties', 'identifier_type',
               existing_type=sa.VARCHAR(),
               comment='VPA / GSTIN / ACCOUNT_IFSC / PAN / PHONE',
               existing_nullable=True)
    op.alter_column('consent_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of first (and only) resolution for SNAPSHOT tokens',
               existing_nullable=True)
    op.alter_column('consent_tokens', 'snapshot_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Score payload captured at mint time (SNAPSHOT scope only)',
               existing_nullable=True)
    op.drop_index('ix_consent_audit_token_created', table_name='consent_audit_log')
    op.create_index('ix_consent_audit_token_created', 'consent_audit_log', ['token_id', sa.text('created_at DESC')], unique=False)
    op.alter_column('consent_audit_log', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Extra context: user-agent, request headers, etc.',
               existing_nullable=True)
    op.alter_column('consent_audit_log', 'requester_ip',
               existing_type=sa.TEXT(),
               comment='IP address of the token resolver (RESOLVED events only)',
               existing_nullable=True)
    op.alter_column('consent_audit_log', 'resolved_scope',
               existing_type=sa.VARCHAR(),
               comment='Scope that was revealed on RESOLVED events',
               existing_nullable=True)
    op.alter_column('consent_audit_log', 'actor',
               existing_type=sa.TEXT(),
               comment='Who performed the action: business UUID or "resolver" or "system"',
               existing_nullable=True)
    op.alter_column('consent_audit_log', 'action',
               existing_type=sa.VARCHAR(),
               comment='MINTED | RESOLVED | REVOKED | EXPIRED',
               existing_nullable=False)
    op.alter_column('consent_audit_log', 'business_id',
               existing_type=sa.UUID(),
               comment='FK → businesses.id (denormalised for fast audit queries)',
               existing_nullable=False)
    op.alter_column('consent_audit_log', 'token_id',
               existing_type=sa.UUID(),
               comment='FK → consent_tokens.id',
               existing_nullable=False)
    op.alter_column('consent_audit_log', 'id',
               existing_type=sa.UUID(),
               comment='Primary key',
               existing_nullable=False)
    op.alter_column('accounts', 'balance_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of the balance snapshot from AA Summary.balanceDateTime',
               existing_nullable=True)
    op.alter_column('accounts', 'balance',
               existing_type=sa.BIGINT(),
               comment='Latest known balance in minor units (paise)',
               existing_nullable=True)
    op.alter_column('accounts', 'ifsc_code',
               existing_type=sa.VARCHAR(length=11),
               comment='Bank IFSC code',
               existing_nullable=True)
    op.alter_column('accounts', 'account_type',
               existing_type=sa.VARCHAR(),
               comment='SAVINGS / CURRENT / OVERDRAFT / CC — from AA Summary.type',
               existing_nullable=True)
    op.alter_column('accounts', 'masked_account_number',
               existing_type=sa.VARCHAR(),
               comment='e.g. XXXXXXXX6053 — safe to store unencrypted',
               existing_nullable=True)
    op.create_table('dashboard_insights',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('insight_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dashboard_insights_pkey')
    )
    op.create_index('ix_dashboard_insights_data_hash', 'dashboard_insights', ['data_hash'], unique=False)
    op.create_index('ix_dashboard_insights_business_id', 'dashboard_insights', ['business_id'], unique=False)
    # ### end Alembic commands ###
