"""add ai_explanation back

Revision ID: d30a8bcb1cb3
Revises: c07e52ec8bef
Create Date: 2026-07-21 20:50:59.859954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30a8bcb1cb3'
down_revision = 'c07e52ec8bef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_snapshots', sa.Column('ai_explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score_snapshots', 'ai_explanation')
    # ### end Alembic commands ###
